// 10 Production-Grade Technical Career Roadmaps (Strictly Structured from Basic to Advanced).

export interface RoadmapPhaseCatalogItem {
  phaseNumber: number;
  title: string;
  objective: string;
  durationWeeks: number;
  skills: string[];
  topics: string[];
  practiceTasks: string[];
  projects: string[];
  milestone: string;
}

export interface CareerRoadmapCatalogItem {
  id: string;
  slug: string;
  title: string;
  category: string;
  targetRole: string;
  level: string;
  estimatedDurationWeeks: number;
  summary: string;
  primarySkills: string[];
  phases: RoadmapPhaseCatalogItem[];
  finalMilestone: string;
}

export const PRODUCTION_ROADMAPS_CATALOG: CareerRoadmapCatalogItem[] = [
  {
    id: 'roadmap-backend-java-spring',
    slug: 'backend-java-spring-boot',
    title: 'Java & Spring Boot Backend Developer: Zero to Production Architect',
    category: 'Backend',
    targetRole: 'Backend Java Developer',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 16,
    summary: 'A step-by-step career path starting from absolute Core Java 21 fundamentals, OOP principles & Collections to Spring Boot 3 REST APIs, Spring Data JPA, Microservices, and enterprise production deployment.',
    primarySkills: ['Java', 'Core Java OOP', 'Spring Boot', 'Spring Data JPA', 'PostgreSQL', 'Docker', 'System Design'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Core Java 21 Basics, OOP & Collections Fundamentals (Beginner)',
        objective: 'Start from absolute scratch: master Java syntax, data types, control flow, Object-Oriented Programming (Inheritance, Polymorphism, Encapsulation, Abstraction), Exception Handling, and the Collections Framework.',
        durationWeeks: 4,
        skills: ['Java', 'Core Java OOP', 'Data Structures', 'Problem Solving'],
        topics: [
          'Java 21 Setup, JDK, JVM & Bytecode Mechanics',
          'Variables, Primitive Data Types & Control Flow (Loops, If-Else, Switch Expressions)',
          'Classes, Objects, Constructors, Methods & Access Modifiers (public/private/protected)',
          '4 Pillars of OOP: Encapsulation, Inheritance, Polymorphism & Abstraction',
          'Interfaces, Abstract Classes & Default Methods',
          'Exception Handling (Checked vs Unchecked, try-catch-finally, Custom Exceptions)',
          'Java Collections Framework (ArrayList, LinkedList, HashMap, HashSet, PriorityQueue)',
          'Java 8+ Modern Features: Lambdas, Streams API & Optional Type',
        ],
        practiceTasks: [
          'Build an interactive console-based Student Grade & Banking System using OOP',
          'Implement CRUD operations in memory using HashMap and ArrayList',
          'Write unit tests for business logic using JUnit 5',
        ],
        projects: ['Console-Based Banking & Student Management System with OOP'],
        milestone: 'Core Java syntax, OOP architecture, and Collections Framework verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Spring Boot 3, REST APIs & Spring Data JPA Persistence (Intermediate)',
        objective: 'Build real-world web backends: master Dependency Injection, Spring MVC controllers, request validation, PostgreSQL database integration with Spring Data JPA & Hibernate ORM.',
        durationWeeks: 4,
        skills: ['Spring Boot', 'Spring Data JPA', 'REST APIs', 'PostgreSQL', 'Hibernate'],
        topics: [
          'Spring Core: Inversion of Control (IoC) & Dependency Injection (@Component, @Service, @Autowired)',
          'Building REST Controllers (@RestController, @GetMapping, @PostMapping, @PutMapping, @DeleteMapping)',
          'DTO Pattern, Request Validation (@Valid, @NotNull, @Size) & Global Exception Handling (@ControllerAdvice)',
          'Spring Data JPA & Hibernate Relational Mapping (@Entity, @Table, @Id, @OneToMany, @ManyToOne)',
          'Connecting PostgreSQL, Writing Custom JPQL Queries & Pagination / Sorting',
          'API Contract Documentation with Swagger / OpenAPI 3',
        ],
        practiceTasks: [
          'Build full CRUD REST APIs with Swagger documentation and PostgreSQL database',
          'Implement entity relationships with cascading and lazy fetching optimization',
        ],
        projects: ['E-Commerce Product Catalog & Order Management REST API with PostgreSQL'],
        milestone: 'Full-stack Spring Boot REST API persistence and CRUD operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Spring Security, JWT Authentication & Microservices (Advanced)',
        objective: 'Harden APIs with stateless JWT authentication, break monoliths into microservices with API Gateway, add Redis caching, and containerize with Docker.',
        durationWeeks: 4,
        skills: ['Spring Security', 'JWT', 'Microservices', 'Redis', 'Docker'],
        topics: [
          'Spring Security 6 Architecture & Stateless JWT Token Verification Filters',
          'User Authentication, BCrypt Password Hashing & Role-Based Access Control (RBAC)',
          'Microservices Architecture: Service Discovery (Eureka) & Spring Cloud Gateway',
          'Sub-Millisecond In-Memory Caching with Redis for High-Throughput Endpoints',
          'Containerization with Multi-Stage Dockerfile and Docker Compose Orchestration',
        ],
        practiceTasks: [
          'Build secure user signup/login with JWT verification and password encryption',
          'Dockerize Spring Boot backend and PostgreSQL database using Docker Compose',
        ],
        projects: ['Secure Multi-Service FinTech Digital Wallet with Redis & Docker'],
        milestone: 'Secured microservices with authentication, caching, and containerization verified',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Kafka Event Streaming, Cloud Deployment & Mock Interview Prep (Capstone)',
        objective: 'Add asynchronous event streaming with Apache Kafka, deploy to Cloud with automated CI/CD pipelines, optimize database queries, and master technical interview questions.',
        durationWeeks: 4,
        skills: ['Kafka', 'CI/CD Pipelines', 'System Design', 'Interview Prep', 'Java Concurrency'],
        topics: [
          'Apache Kafka Event-Driven Architecture (Producers, Consumers & Partitions)',
          'PostgreSQL Indexing & Query Execution Plans (EXPLAIN ANALYZE)',
          'Java 21 Virtual Threads & Structured Concurrency Basics',
          'Automated GitHub Actions CI/CD Deployment to Cloud (AWS/Render)',
          'Top 50 Java & Spring Boot Technical Interview Questions & System Design',
        ],
        practiceTasks: [
          'Implement event-driven asynchronous notification and audit logging using Kafka',
          'Complete 1-on-1 mock technical interview with senior mentor Priya Sharma',
        ],
        projects: ['Production-Grade High-Throughput FinTech Payment Gateway Capstone'],
        milestone: 'Job-Ready Professional Java & Spring Boot Developer',
      },
    ],
    finalMilestone: 'Certified Java & Spring Boot Backend Developer',
  },
  {
    id: 'roadmap-fullstack-nextjs',
    slug: 'fullstack-nextjs-typescript',
    title: 'Full Stack Next.js 15 & TypeScript: Zero to Production Architect',
    category: 'Full Stack',
    targetRole: 'Full Stack Engineer',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 14,
    summary: 'A complete step-by-step career path starting from HTML5/CSS3/JavaScript ES6+ fundamentals and strict TypeScript to React 19, Next.js App Router, Prisma ORM, PostgreSQL, and cloud deployment.',
    primarySkills: ['JavaScript', 'TypeScript', 'React', 'Next.js', 'PostgreSQL', 'Prisma ORM', 'Tailwind CSS'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Web Fundamentals, JavaScript ES6+ & TypeScript Basics (Beginner)',
        objective: 'Master foundational modern JavaScript (ES6+), DOM manipulation, async/await, and strict TypeScript types and interfaces.',
        durationWeeks: 3,
        skills: ['JavaScript', 'TypeScript', 'HTML5', 'CSS3'],
        topics: [
          'Modern JavaScript ES6+ (let/const, Arrow Functions, Destructuring, Spread, Promises, Async/Await)',
          'TypeScript Basics: Types, Interfaces, Generics, Enums & Type Narrowing',
          'DOM Manipulation, Event Loop & Fetch API',
          'Modular Code Organization & NPM Package Management',
        ],
        practiceTasks: ['Build interactive task dashboard in pure TypeScript', 'Implement asynchronous data fetching with typed interfaces'],
        projects: ['TypeScript Interactive Expense Tracker & Analytics Dashboard'],
        milestone: 'JavaScript and TypeScript language fundamentals verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: React 19 Core, Tailwind CSS & Next.js App Router (Intermediate)',
        objective: 'Build responsive modern UIs with React 19 component trees, hooks, Tailwind CSS utility styling, and Next.js App Router page layouts.',
        durationWeeks: 4,
        skills: ['React', 'Next.js', 'Tailwind CSS'],
        topics: [
          'React 19 Component Architecture, Props & State Management (useState, useEffect, useMemo)',
          'Custom Hooks & Component Reusability',
          'Tailwind CSS Utility Styling & Responsive Layouts',
          'Next.js 15 App Router: Server Components vs Client Components, Nested Layouts & Dynamic Routing',
        ],
        practiceTasks: ['Build reusable UI component system (Modal, Card, Tabs, Inputs)', 'Implement client-side state filtering and search'],
        projects: ['Modern Responsive Freelance Services Marketplace UI with Next.js'],
        milestone: 'React 19 and Next.js frontend architecture operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Server Actions, PostgreSQL Database & Prisma ORM (Advanced)',
        objective: 'Implement server-side mutations, relational PostgreSQL schemas with Prisma ORM, and secure authentication.',
        durationWeeks: 4,
        skills: ['PostgreSQL', 'Prisma ORM', 'REST APIs', 'JWT', 'Authentication'],
        topics: [
          'Next.js Server Actions & Form Mutations with Zod Validation',
          'Prisma ORM Relational Schemas, Migrations & Foreign Keys',
          'PostgreSQL Database Indexing & Query Execution',
          'Stateless JWT Authentication & Protected Route Middleware',
          'Redis In-Memory Caching for Fast Page Loads',
        ],
        practiceTasks: ['Build complete CRUD backend with Prisma ORM and PostgreSQL', 'Implement user auth with secure session cookies and middleware'],
        projects: ['Full-Stack SaaS Collaborative Workspace with Relational Database'],
        milestone: 'Full-stack persistence and authentication flows operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: CI/CD Deployment, Performance Optimization & Capstone (Job-Ready)',
        objective: 'Containerize application with Docker, set up automated CI/CD pipelines, optimize Core Web Vitals, and prepare for interviews.',
        durationWeeks: 3,
        skills: ['Docker', 'CI/CD Pipelines', 'Performance Optimization', 'Interview Prep'],
        topics: [
          'Multi-Stage Docker Builds & Cloud Deployment (Vercel / Render)',
          'Automated CI/CD Workflows with GitHub Actions',
          'Core Web Vitals Optimization (LCP, CLS, INP) & Lighthouse 95+',
          'Full-Stack System Design & Technical Mock Interviews',
        ],
        practiceTasks: ['Achieve 95+ Google Lighthouse score on production deployment', 'Conduct 1-on-1 code review with senior mentor Vikram Patel'],
        projects: ['Production-Grade Enterprise SaaS Application with Complete CI/CD'],
        milestone: 'Job-Ready Full Stack Next.js & TypeScript Engineer',
      },
    ],
    finalMilestone: 'Certified Full Stack Next.js & TypeScript Candidate',
  },
  {
    id: 'roadmap-genai-llm-rag',
    slug: 'generative-ai-llm-rag',
    title: 'Python AI, Machine Learning & Generative AI RAG Specialist',
    category: 'AI / Machine Learning',
    targetRole: 'AI & LLM Engineer',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 14,
    summary: 'From Python programming basics and NumPy/Pandas data wrangling to PyTorch machine learning, PostgreSQL pgvector embeddings, and LangChain autonomous AI agents.',
    primarySkills: ['Python', 'Machine Learning', 'PyTorch', 'LangChain & RAG', 'PostgreSQL', 'FastAPI'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Python Basics, Data Structures & NumPy/Pandas Wrangling (Beginner)',
        objective: 'Master Python syntax, lists, dictionaries, functions, OOP in Python, and vectorized data wrangling with NumPy and Pandas.',
        durationWeeks: 3,
        skills: ['Python', 'Data Science', 'Problem Solving'],
        topics: [
          'Python 3.12 Syntax, Variables, Loops & Functions',
          'Data Structures: Lists, Tuples, Dictionaries & Sets',
          'Object-Oriented Programming in Python (Classes, Methods, Inheritance)',
          'Vectorized Numerical Computing with NumPy',
          'Data Wrangling, Cleaning & Exploratory Analysis with Pandas',
        ],
        practiceTasks: ['Analyze messy real-world datasets and generate statistical summaries', 'Write modular Python scripts with error handling'],
        projects: ['Data Analysis & Automated Insights Generation Suite with Pandas'],
        milestone: 'Python programming and numerical computing foundations verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Machine Learning Fundamentals, Scikit-Learn & PyTorch (Intermediate)',
        objective: 'Learn supervised learning, regression, classification, neural network tensors, and text tokenization with PyTorch.',
        durationWeeks: 4,
        skills: ['Machine Learning', 'PyTorch', 'Deep Learning'],
        topics: [
          'Supervised Learning: Linear Regression, Logistic Regression & Random Forests',
          'Model Evaluation: Precision, Recall, F1-Score & ROC-AUC',
          'PyTorch Tensors, Autograd & Neural Network Layers',
          'Text Preprocessing, Tokenization & Word Embeddings',
        ],
        practiceTasks: ['Train classification models and evaluate performance metrics', 'Build neural network text classifier in PyTorch'],
        projects: ['Customer Churn & Sentiment Analysis Neural Classifier with PyTorch'],
        milestone: 'Machine learning algorithms and PyTorch neural networks operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Vector Embeddings, PostgreSQL pgvector & RAG Pipelines (Advanced)',
        objective: 'Design production Retrieval-Augmented Generation (RAG) with vector embeddings, semantic search, and PostgreSQL pgvector.',
        durationWeeks: 4,
        skills: ['LangChain & RAG', 'PostgreSQL', 'LLM Engineering'],
        topics: [
          'Vector Embedding Models (1536-dim) & Cosine Similarity Projections',
          'PostgreSQL pgvector Extension (<=> Cosine Operator & HNSW Indexing)',
          'Document Chunking Strategies (Recursive Character Splitting)',
          'Grounded Prompt Engineering & Citation Generation',
          'LangChain Autonomous Agents & Tool Calling',
        ],
        practiceTasks: ['Ingest 500+ technical PDF documents and perform semantic vector search', 'Build grounded RAG assistant with source citations'],
        projects: ['Enterprise Document Intelligence & RAG Chatbot with pgvector'],
        milestone: 'End-to-end grounded RAG pipeline operational with high recall',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: FastAPI Serving, Docker Deployment & MLOps Capstone (Job-Ready)',
        objective: 'Deploy AI models as high-speed async FastAPI microservices with streaming SSE, Docker containerization, and mentor audit.',
        durationWeeks: 3,
        skills: ['FastAPI', 'Docker', 'MLOps', 'Interview Prep'],
        topics: [
          'Asynchronous FastAPI REST Endpoints & Streaming Server-Sent Events (SSE)',
          'Pydantic Data Validation & Schema Serialization',
          'Containerization with Docker & Cloud Deployment',
          'MLOps Best Practices, Rate Limiting & Latency Benchmarks',
        ],
        practiceTasks: ['Build async streaming API gateway for LLM completions', 'Complete 1-on-1 AI architecture review with mentor Sneha Iyer'],
        projects: ['Production Scalable Generative AI API Gateway with Real-Time Streaming'],
        milestone: 'Job-Ready Production Generative AI & RAG Engineer',
      },
    ],
    finalMilestone: 'Certified Generative AI & RAG Pipeline Specialist',
  },
  {
    id: 'roadmap-cloud-devops-k8s',
    slug: 'cloud-devops-kubernetes-sre',
    title: 'Cloud DevOps, Kubernetes & AWS Infrastructure SRE: Zero to Hero',
    category: 'DevOps & Cloud',
    targetRole: 'Cloud DevOps Architect',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 15,
    summary: 'From Linux command line, shell scripting, and Git to Docker containerization, Kubernetes cluster orchestration on AWS, Terraform IaC, and SRE monitoring.',
    primarySkills: ['Linux', 'Docker', 'Kubernetes', 'AWS', 'Terraform', 'CI/CD Pipelines'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Linux Command Line, Shell Scripting & Git Fundamentals (Beginner)',
        objective: 'Master Linux terminal navigation, file permissions, Bash scripting, process management, and Git version control.',
        durationWeeks: 3,
        skills: ['Linux', 'Shell Scripting', 'Git', 'Networking'],
        topics: [
          'Linux File System, Permissions (chmod/chown) & Process Management (ps, top, systemctl)',
          'Bash Shell Scripting & Automated Task Scheduling (Cron Jobs)',
          'Git Branching, Merging, Rebasing & Pull Request Workflows',
          'Networking Basics: TCP/IP, DNS, Subnets, SSH Keys & Firewalls',
        ],
        practiceTasks: ['Write automated Bash script for server health monitoring and log rotation', 'Configure secure SSH keys and Linux firewall rules'],
        projects: ['Automated Linux Server Provisioning & Health Monitoring Suite'],
        milestone: 'Linux administration, shell scripting, and Git workflows verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Docker Containerization & Multi-Stage Builds (Intermediate)',
        objective: 'Containerize microservices, create optimized multi-stage Dockerfiles, manage volumes, and orchestrate with Docker Compose.',
        durationWeeks: 4,
        skills: ['Docker', 'Microservices', 'Container Security'],
        topics: [
          'Docker Architecture: Images, Containers, Registries & Daemons',
          'Writing Optimized Multi-Stage Dockerfiles (Node.js, Java, Python)',
          'Container Networking, Port Forwarding & Persistent Volumes',
          'Docker Compose Multi-Container Stacks (App + Database + Redis)',
        ],
        practiceTasks: ['Build sub-50MB production Docker container images', 'Set up multi-container local development stack with Docker Compose'],
        projects: ['Production-Hardened Microservices Container Suite with Docker Compose'],
        milestone: 'Docker containerization and multi-stage builds operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Kubernetes Cluster Orchestration & Helm Packaging (Advanced)',
        objective: 'Deploy and scale containerized applications on Kubernetes with Pods, Deployments, Services, Ingress, and Helm charts.',
        durationWeeks: 4,
        skills: ['Kubernetes', 'Helm', 'Cloud Native'],
        topics: [
          'Kubernetes Architecture: Control Plane, Nodes, Kubelet & etcd',
          'Deployments, Pods, ReplicaSets & Horizontal Pod Autoscaler (HPA)',
          'Cluster Networking: Services (ClusterIP, NodePort, LoadBalancer) & Ingress Controllers',
          'ConfigMaps, Secrets, RBAC & Helm Chart Packaging',
        ],
        practiceTasks: ['Deploy 5-tier microservices application on local Minikube / K8s cluster', 'Configure automated auto-scaling under simulated traffic spike'],
        projects: ['High-Availability Kubernetes Cluster with Automated Autoscaling & Ingress'],
        milestone: 'Kubernetes cluster deployment and rolling updates operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Terraform Infrastructure as Code, CI/CD & Observability (Job-Ready)',
        objective: 'Provision AWS infrastructure with Terraform, automate GitHub Actions CI/CD pipelines, and set up Prometheus/Grafana SRE monitoring.',
        durationWeeks: 4,
        skills: ['AWS', 'Terraform', 'CI/CD Pipelines', 'Observability', 'Prometheus'],
        topics: [
          'Terraform State Management, HCL Syntax & Modular AWS Provisioning (VPC, EKS, RDS)',
          'Automated CI/CD Delivery Pipelines with GitHub Actions',
          'Prometheus Metric Scraping, Alertmanager & Grafana Dashboards',
          'SRE Best Practices, Incident Management & Technical Mock Interviews',
        ],
        practiceTasks: ['Write modular Terraform code to provision multi-AZ AWS infrastructure', 'Complete 1-on-1 DevOps architecture audit with mentor Arjun Nair'],
        projects: ['Production Enterprise Cloud SRE & Automated CI/CD Platform'],
        milestone: 'Job-Ready Cloud DevOps & SRE Engineer',
      },
    ],
    finalMilestone: 'Certified Cloud DevOps & Kubernetes SRE Specialist',
  },
  {
    id: 'roadmap-frontend-uiux-react',
    slug: 'frontend-uiux-design-systems',
    title: 'Frontend React 19 & UI/UX Design System: Zero to Lead Engineer',
    category: 'Frontend',
    targetRole: 'Senior Frontend Engineer',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 12,
    summary: 'From UI/UX design principles in Figma and modern HTML5/CSS3/JavaScript to React 19 component libraries, Tailwind CSS design tokens, and web performance optimization.',
    primarySkills: ['UI/UX Design (Figma)', 'JavaScript', 'TypeScript', 'React', 'Tailwind CSS'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: UI/UX Principles, Figma Wireframing & Responsive CSS (Beginner)',
        objective: 'Master user interface design principles, Figma wireframing, typography, color palettes, and modern responsive CSS layouts.',
        durationWeeks: 3,
        skills: ['UI/UX Design (Figma)', 'HTML5', 'CSS3', 'Accessibility'],
        topics: [
          'UI/UX Design Principles: Visual Hierarchy, Typography, Spacing & Contrast',
          'Figma Fundamentals: Frames, Auto-Layout, Components & Variants',
          'Modern Responsive CSS: Flexbox, CSS Grid & Media Queries',
          'WCAG 2.1 AA Accessibility Guidelines & Semantic HTML5 Elements',
        ],
        practiceTasks: ['Design complete 10-screen responsive mobile and desktop web prototype in Figma', 'Build responsive landing page matching Figma design pixel-for-pixel'],
        projects: ['Enterprise Figma Design System & Responsive Landing Page'],
        milestone: 'UI/UX design principles and responsive layouts verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Modern JavaScript (ES6+), React 19 & Tailwind CSS (Intermediate)',
        objective: 'Translate designs into React 19 component trees, master custom hooks, state management, and Tailwind CSS design tokens.',
        durationWeeks: 3,
        skills: ['React', 'JavaScript', 'Tailwind CSS', 'TypeScript'],
        topics: [
          'Modern ES6+ JavaScript: Arrow Functions, Array Methods, Async/Await',
          'React 19 Components, Props, useState & useEffect Hooks',
          'Tailwind CSS Utility Classes, Custom Config & Tokenization',
          'Form Handling with React Hook Form & Zod Validation',
        ],
        practiceTasks: ['Build interactive component primitives (Buttons, Modals, Dropdowns, Cards)', 'Implement live filtering, search, and pagination in React'],
        projects: ['Interactive SaaS Component Library & Design System Showcase'],
        milestone: 'React component library and design tokens operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Next.js App Router, Micro-Interactions & State Sync (Advanced)',
        objective: 'Assemble full web applications with Next.js App Router, TanStack Query for server state, and fluid animations.',
        durationWeeks: 3,
        skills: ['Next.js', 'TanStack Query', 'Framer Motion', 'TypeScript'],
        topics: [
          'Next.js 15 App Router Layouts, Pages & Server Components',
          'Server State Caching & Optimistic Updates with TanStack Query',
          'Smooth Micro-Interactions & Transitions with Framer Motion',
          'Complex Data Visualizations with Recharts / Chart.js',
        ],
        practiceTasks: ['Build interactive analytics dashboard with live charts and real-time updates', 'Implement smooth animated transitions between routes'],
        projects: ['Real-Time SaaS Analytics Dashboard & Reporting Suite'],
        milestone: 'Complex data dashboard and interactive animations operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Web Performance Optimization, E2E Testing & Portfolio (Job-Ready)',
        objective: 'Optimize Core Web Vitals to 95+ Lighthouse score, write Playwright E2E tests, and complete 1-on-1 mentor portfolio audit.',
        durationWeeks: 3,
        skills: ['Web Performance', 'Playwright', 'Interview Prep', 'Mentorship'],
        topics: [
          'Core Web Vitals Tuning (LCP, CLS, INP) & Code Splitting',
          'Automated End-to-End Testing with Playwright',
          'Frontend System Design & Technical Mock Interviews',
          'Live Portfolio Presentation & Mentor Review',
        ],
        practiceTasks: ['Achieve 98+ Google Lighthouse performance score on deployed app', 'Complete 1-on-1 portfolio audit with mentor Ananya Deshmukh'],
        projects: ['High-Performance Digital Product Portfolio with 98+ Lighthouse Score'],
        milestone: 'Job-Ready Senior Frontend Engineer & UI/UX Specialist',
      },
    ],
    finalMilestone: 'Certified Frontend & UI/UX Design System Specialist',
  },
  {
    id: 'roadmap-mobile-flutter-react-native',
    slug: 'mobile-app-development-flutter',
    title: 'Cross-Platform Mobile App Architect (Flutter & React Native): Zero to Hero',
    category: 'Mobile Development',
    targetRole: 'Mobile App Developer',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 14,
    summary: 'From programming fundamentals (Dart / TypeScript) to building high-performance iOS and Android apps with Flutter, React Native, offline SQLite storage, and App Store publishing.',
    primarySkills: ['Flutter', 'Dart', 'React Native', 'TypeScript', 'Mobile Development', 'Firebase'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Dart / TypeScript Basics & Mobile UI Fundamentals (Beginner)',
        objective: 'Learn core programming syntax (Dart or TypeScript), widget trees, flexbox layout, and mobile navigation.',
        durationWeeks: 3,
        skills: ['Dart', 'TypeScript', 'Flutter', 'React Native'],
        topics: [
          'Dart / TypeScript Syntax, Data Types, Control Flow & Functions',
          'Flutter Widget Tree (Stateless & Stateful) / React Native Components',
          'Mobile Layouts: Column, Row, Stack, Padding & Responsive Sizing',
          'Basic Navigation & Routing Stacks between Screens',
        ],
        practiceTasks: ['Build multi-screen mobile UI with custom themes and dark mode', 'Implement form validation on mobile inputs'],
        projects: ['Cross-Platform Mobile Habits & Task Tracking App'],
        milestone: 'Mobile UI fundamentals and responsive layouts verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: State Management & REST/GraphQL API Integration (Intermediate)',
        objective: 'Connect mobile apps to web APIs, parse JSON responses, and manage app state with Riverpod / Redux.',
        durationWeeks: 4,
        skills: ['State Management', 'REST APIs', 'GraphQL', 'Mobile Development'],
        topics: [
          'State Management Patterns (Riverpod / Bloc in Flutter; Zustand / Redux in React Native)',
          'HTTP Networking, Async/Await & JSON Serialization',
          'Infinite Scroll Pagination & Pull-to-Refresh Lists',
          'Secure Local Token Storage (FlutterSecureStorage / EncryptedStorage)',
        ],
        practiceTasks: ['Build live product catalog with category filters and pagination', 'Implement secure user authentication flow with JWT tokens'],
        projects: ['E-Commerce Mobile Shopping App with Cart & Order Flow'],
        milestone: 'State management and cloud API connectivity operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Offline-First SQLite Persistence & Native Device APIs (Advanced)',
        objective: 'Implement offline-first local database caching, background sync, push notifications, and native hardware sensors (Camera, GPS, Biometrics).',
        durationWeeks: 4,
        skills: ['SQLite', 'Offline Storage', 'Firebase', 'Geolocation'],
        topics: [
          'Local Database Storage (SQLite / Drift / Hive / WatermelonDB)',
          'Offline Synchronization & Conflict Resolution Queue',
          'Native Hardware APIs: Geolocation Tracking, Camera & Biometric Auth',
          'Push Notifications with Firebase Cloud Messaging (FCM)',
        ],
        practiceTasks: ['Build offline-first data synchronization engine', 'Implement biometric fingerprint / FaceID login'],
        projects: ['Location-Aware On-Demand Delivery & Ride Tracking Mobile App'],
        milestone: 'Offline persistence and hardware sensor integration operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Automated Testing, Fastlane CI/CD & App Store Publishing (Job-Ready)',
        objective: 'Automate build and release pipelines using Fastlane, write automated tests, and publish to Apple App Store and Google Play.',
        durationWeeks: 3,
        skills: ['CI/CD Pipelines', 'Fastlane', 'App Store Deploy', 'Interview Prep'],
        topics: [
          'Automated Unit & Widget Testing in Mobile',
          'Fastlane Automated Code Signing & Release Builds',
          'Google Play Store & Apple App Store Guidelines & Submission',
          'Mobile Architecture Mock Interviews with Senior Mentor',
        ],
        practiceTasks: ['Set up automated Fastlane build pipeline for iOS and Android', 'Complete 1-on-1 code audit with mentor Pooja Verma'],
        projects: ['Production Published Mobile App on App Store & Google Play'],
        milestone: 'Job-Ready Mobile Application Architect',
      },
    ],
    finalMilestone: 'Certified Mobile App Architect (Flutter & React Native)',
  },
  {
    id: 'roadmap-data-engineering-etl',
    slug: 'data-engineering-postgresql-etl',
    title: 'Data Engineering, SQL & Real-Time ETL Pipeline: Zero to Architect',
    category: 'Database & Architecture',
    targetRole: 'Data Engineer',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 14,
    summary: 'From relational SQL queries, schema modeling, and Python data pipelines to distributed Apache Spark, PostgreSQL partitioning, and Kafka streaming architectures.',
    primarySkills: ['SQL', 'Python', 'PostgreSQL', 'Data Engineering', 'Kafka', 'Redis'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Relational SQL Mastery, Schema Design & Python Basics (Beginner)',
        objective: 'Master relational database theory, complex SQL queries (JOINs, Group By, Subqueries), and Python file/data wrangling.',
        durationWeeks: 3,
        skills: ['SQL', 'PostgreSQL', 'Python'],
        topics: [
          'Relational Database Modeling, Normalization (1NF, 2NF, 3NF) & Primary/Foreign Keys',
          'Advanced SQL Queries: INNER/LEFT/FULL JOINs, GROUP BY, HAVING & Subqueries',
          'SQL Window Functions (ROW_NUMBER, RANK, DENSE_RANK, LEAD, LAG)',
          'Python Database Connectivity (Psycopg / SQLAlchemy) & File I/O (CSV, JSON, Parquet)',
        ],
        practiceTasks: ['Write complex SQL reports with aggregations and window functions', 'Build automated Python script to ingest CSV files into PostgreSQL'],
        projects: ['Sales & Inventory Relational Analytics Database with Complex SQL Views'],
        milestone: 'Relational database schema design and SQL query mastery verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Python ETL Pipelines, Data Validation & Batch Workflows (Intermediate)',
        objective: 'Build robust Extract-Transform-Load (ETL) pipelines in Python with Pandas, Polars, and schema assertions.',
        durationWeeks: 4,
        skills: ['Python', 'ETL Pipelines', 'Data Engineering', 'Pandas'],
        topics: [
          'ETL Architecture: Extract from REST APIs & SQL, Transform with Polars/Pandas, Load to PostgreSQL',
          'Data Cleaning, Type Casting, Missing Value Imputation & Anomaly Detection',
          'Idempotent Pipeline Execution & Incremental Loading Patterns',
          'Automated Workflow Scheduling with Apache Airflow / Prefect Basics',
        ],
        practiceTasks: ['Build automated pipeline pulling live data from 3 public REST APIs', 'Implement automated data schema validation checks'],
        projects: ['Automated Multi-Source Financial Data Ingestion & ETL Pipeline'],
        milestone: 'Robust batch ETL extraction and validation verified',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Real-Time Stream Processing with Kafka, Redis & Partitioning (Advanced)',
        objective: 'Process live streaming telemetry with Apache Kafka, Redis in-memory analytics, and PostgreSQL declarative table partitioning.',
        durationWeeks: 4,
        skills: ['Kafka', 'Redis', 'PostgreSQL', 'Stream Processing'],
        topics: [
          'Apache Kafka Event Streaming: Topics, Partitions, Consumer Groups & Offsets',
          'Real-time Windowed Aggregations & Metrics Calculation',
          'PostgreSQL Declarative Table Partitioning (Range & List Partitioning) for 10M+ Rows',
          'B-Tree & BRIN Index Optimization on Large Datasets',
        ],
        practiceTasks: ['Build real-time event streaming consumer with Kafka and Redis', 'Partition a massive time-series dataset in PostgreSQL and benchmark query speedups'],
        projects: ['Real-Time High-Throughput E-Commerce Telemetry & Analytics Engine'],
        milestone: 'Real-time event streaming and partitioned database storage operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Cloud Data Warehousing, CI/CD & Portfolio Capstone (Job-Ready)',
        objective: 'Deploy automated data pipelines with Docker, monitoring dashboards, and complete 1-on-1 architecture review with senior mentor.',
        durationWeeks: 3,
        skills: ['Docker', 'CI/CD Pipelines', 'System Design', 'Interview Prep'],
        topics: [
          'Containerized Pipeline Deployment with Docker & GitHub Actions',
          'Data Lineage, Data Quality Monitoring & SLA Alerting',
          'Data Engineering System Design & Technical Mock Interviews',
          'Live Portfolio Presentation & Mentor Review',
        ],
        practiceTasks: ['Pass automated pipeline regression tests and SLA compliance checks', 'Book 1-on-1 architecture review with mentor Karthik Raja'],
        projects: ['Enterprise Data Lakehouse & Real-Time Analytics Platform Capstone'],
        milestone: 'Job-Ready Enterprise Data Engineer',
      },
    ],
    finalMilestone: 'Certified Data Engineering & Pipeline Specialist',
  },
  {
    id: 'roadmap-cybersecurity-oauth2',
    slug: 'cybersecurity-zero-trust-cloud',
    title: 'Cybersecurity & Zero-Trust Cloud Defense Specialist: Zero to Hero',
    category: 'Backend',
    targetRole: 'Cybersecurity Engineer',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 12,
    summary: 'From computer networking and security fundamentals to OWASP Top 10 defense, OAuth2/OIDC token architectures, container security, and cloud penetration testing.',
    primarySkills: ['Cybersecurity', 'Networking', 'Spring Security', 'Docker', 'System Design', 'AWS'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Computer Networks, Operating Systems & Security Basics (Beginner)',
        objective: 'Master TCP/IP networking protocols, packet inspection, Linux security controls, and encryption fundamentals.',
        durationWeeks: 3,
        skills: ['Networking', 'Linux', 'Cybersecurity', 'Cryptography'],
        topics: [
          'OSI & TCP/IP Network Models, IP Subnets, DNS & Routing',
          'Symmetric vs Asymmetric Encryption (AES, RSA, ECC) & Hashing (SHA-256, BCrypt)',
          'TLS/SSL Handshake & HTTPS Public Key Infrastructure (PKI)',
          'Linux Permissions, User Privileges & Network Firewalls (iptables / ufw)',
        ],
        practiceTasks: ['Inspect network packets and TLS certificates using Wireshark', 'Configure Linux firewall rules to block unauthorized inbound ports'],
        projects: ['Network Traffic Analyzer & Security Diagnostics Tool'],
        milestone: 'Networking security and cryptography fundamentals verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: OWASP Top 10 Web Defense & Threat Modeling (Intermediate)',
        objective: 'Audit and remediate SQL injection, XSS, CSRF, broken access control, and implement defensive secure coding practices.',
        durationWeeks: 3,
        skills: ['Secure Coding', 'Web Security', 'OWASP Top 10'],
        topics: [
          'OWASP Top 10 Web Application Security Risks',
          'Preventing SQL Injection (Parameterized Queries & ORMs)',
          'Cross-Site Scripting (XSS) & Content Security Policy (CSP) Headers',
          'Cross-Site Request Forgery (CSRF) Tokens & SameSite Cookies',
        ],
        practiceTasks: ['Perform vulnerability audit on intentionally vulnerable web app using OWASP ZAP', 'Remediate detected vulnerabilities and write automated security tests'],
        projects: ['Web Application Vulnerability Scanner & Remediation Report'],
        milestone: 'OWASP vulnerability remediation and defensive coding verified',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: OAuth2, OIDC & Container Security Hardening (Advanced)',
        objective: 'Implement production OAuth2 authentication servers, PKCE flows, JWT verification, and secure Docker container runtimes.',
        durationWeeks: 3,
        skills: ['Spring Security', 'OAuth2', 'JWT', 'Docker'],
        topics: [
          'OAuth2 Authorization Code Flow with PKCE & OpenID Connect (OIDC)',
          'Cryptographic JWT Verification (RS256) & Key Rotation',
          'Container Security: Minimal Base Images & Vulnerability Scanning (Trivy)',
          'Zero-Trust Network Policies & Secrets Management (AWS Secrets Manager / Vault)',
        ],
        practiceTasks: ['Build dedicated OAuth2 token authorization server', 'Scan Docker container images and eliminate all high/critical CVEs'],
        projects: ['Enterprise Centralized OAuth2 / OIDC Single Sign-On Gateway with Docker'],
        milestone: 'Cryptographic identity and zero-trust container security operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Security Auditing, Incident Response & Portfolio Capstone (Job-Ready)',
        objective: 'Simulate incident response, audit security access logs, and complete 1-on-1 security review with senior cybersecurity mentor.',
        durationWeeks: 3,
        skills: ['Incident Response', 'Security Auditing', 'Interview Prep', 'Mentorship'],
        topics: [
          'Security Event Logging & SIEM Analysis',
          'Incident Response Runbooks & Disaster Recovery',
          'Cybersecurity Technical Mock Interviews',
          'Live Security Audit Demonstration with Mentor',
        ],
        practiceTasks: ['Draft comprehensive security audit and incident response runbook', 'Conduct 1-on-1 security review with mentor Suresh Menon'],
        projects: ['Production Enterprise Zero-Trust Defense & Security Audit Suite'],
        milestone: 'Job-Ready Cybersecurity & Cloud Defense Specialist',
      },
    ],
    finalMilestone: 'Certified Cybersecurity & Zero-Trust Defense Engineer',
  },
  {
    id: 'roadmap-db-performance-redis',
    slug: 'database-performance-redis-caching',
    title: 'PostgreSQL Performance, Indexing & Redis Caching: Zero to Architect',
    category: 'Database & Architecture',
    targetRole: 'Database Architect',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 12,
    summary: 'From relational database design and SQL fundamentals to B-Tree indexing strategies, EXPLAIN ANALYZE query tuning, and sub-millisecond Redis distributed caching.',
    primarySkills: ['SQL', 'PostgreSQL', 'Redis', 'Database & Architecture', 'System Design'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Database Theory, Relational Modeling & Core SQL (Beginner)',
        objective: 'Master relational schema design, primary/foreign keys, constraints, and standard SQL queries.',
        durationWeeks: 3,
        skills: ['SQL', 'PostgreSQL', 'Database Design'],
        topics: [
          'Relational Database Modeling & Normalization (1NF to 3NF)',
          'Table Constraints (PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK, NOT NULL)',
          'Writing Efficient SQL Queries (JOINs, Aggregations, Grouping, Subqueries)',
          'PostgreSQL Data Types (UUID, JSONB, Timestamps, Numeric)',
        ],
        practiceTasks: ['Design normalized schema for e-commerce platform with 8 tables', 'Write SQL queries calculating monthly revenue, user retention, and order stats'],
        projects: ['E-Commerce Relational Database Schema & Reporting Suite'],
        milestone: 'Relational database modeling and SQL foundations verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: B-Tree Indexing, Composite Indexes & EXPLAIN Tuning (Intermediate)',
        objective: 'Understand B-Tree index mechanics, multi-column composite index ordering, and reading EXPLAIN (ANALYZE, BUFFERS) plans.',
        durationWeeks: 3,
        skills: ['PostgreSQL', 'Database Indexing', 'SQL Optimization'],
        topics: [
          'B-Tree, GIN, GiST & BRIN Index Mechanics in PostgreSQL',
          'Composite Index Column Ordering Rules & Leftmost Prefix Matching',
          'Index Scan vs Bitmap Index Scan vs Sequential Scan',
          'Interpreting EXPLAIN (ANALYZE, BUFFERS) Execution Plans',
        ],
        practiceTasks: ['Optimize slow queries from 2.5s down to <5ms using composite indexes', 'Profile buffer cache hit ratios in PostgreSQL'],
        projects: ['Database Query Optimization & Performance Benchmark Report'],
        milestone: 'B-Tree indexing and query plan optimization verified',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Redis In-Memory Architectures & Distributed Caching (Advanced)',
        objective: 'Design high-speed caching layers with Redis strings, hashes, sorted sets, pub/sub, and Redlock distributed locking.',
        durationWeeks: 3,
        skills: ['Redis', 'Distributed Caching', 'System Design'],
        topics: [
          'Redis Data Structures: Strings, Hashes, Lists, Sets & Sorted Sets',
          'Cache-Aside, Write-Through & Write-Behind Caching Patterns',
          'Cache Stampede Mitigation & Mutex Locks',
          'Distributed Locking with Redlock Algorithm',
        ],
        practiceTasks: ['Implement cache-aside pattern with automatic TTL invalidation', 'Build distributed rate limiter using Redis sorted sets'],
        projects: ['Low-Latency Distributed Redis Cache Layer with Sentinel Failover'],
        milestone: 'Sub-millisecond distributed caching operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Replication, Partitioning & Database System Design (Job-Ready)',
        objective: 'Implement PostgreSQL logical replication, table partitioning strategies, and complete 1-on-1 review with mentor.',
        durationWeeks: 3,
        skills: ['PostgreSQL', 'Replication', 'System Design', 'Mentorship'],
        topics: [
          'Primary-Replica Streaming Replication & Read Load Balancing',
          'Declarative Table Partitioning for Multi-Million Row Tables',
          'Connection Pooling Optimization with PgBouncer',
          'Database Architecture Technical Mock Interviews',
        ],
        practiceTasks: ['Configure primary-replica streaming replication on PostgreSQL', 'Complete 1-on-1 database design review with mentor Karthik Raja'],
        projects: ['Enterprise Scalable Multi-Node Database & Cache Cluster Architecture'],
        milestone: 'Job-Ready Principal Database & Storage Architect',
      },
    ],
    finalMilestone: 'Certified Database Performance & Caching Specialist',
  },
  {
    id: 'roadmap-distributed-systems-go',
    slug: 'distributed-systems-golang-kafka',
    title: 'Go (Golang) Microservices & Distributed Event Systems: Zero to Architect',
    category: 'Backend',
    targetRole: 'Distributed Systems Architect',
    level: 'Beginner to Advanced',
    estimatedDurationWeeks: 15,
    summary: 'From Go language basics, structs, interfaces, and goroutines to building high-throughput gRPC backends, Apache Kafka event streaming, and fault-tolerant microservices.',
    primarySkills: ['Go (Golang)', 'REST APIs', 'gRPC', 'PostgreSQL', 'Kafka', 'Docker'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Go (Golang) Language Basics, Structs & Goroutines (Beginner)',
        objective: 'Master Go syntax, pointers, structs, interfaces, slices, maps, error handling, and basic concurrency with goroutines and channels.',
        durationWeeks: 4,
        skills: ['Go (Golang)', 'Concurrency', 'Problem Solving'],
        topics: [
          'Go Setup, Syntax, Variables, Control Flow & Functions',
          'Pointers, Structs, Methods & Custom Types',
          'Interfaces, Type Assertions & Composition (No Inheritance)',
          'Error Handling Idioms in Go (errors.Is, errors.As, custom errors)',
          'Goroutines, Channels & sync.WaitGroup Synchronization',
        ],
        practiceTasks: ['Build interactive CLI tool in Go with concurrent worker goroutines', 'Write unit tests and benchmarks using standard testing package'],
        projects: ['High-Performance Concurrent File Processing & Analytics CLI in Go'],
        milestone: 'Go language fundamentals and concurrent execution verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: RESTful Web APIs, PostgreSQL & GORM in Go (Intermediate)',
        objective: 'Build production web APIs in Go with routing (Chi / Gin), database integration with PostgreSQL, and JSON serialization.',
        durationWeeks: 4,
        skills: ['Go (Golang)', 'REST APIs', 'PostgreSQL', 'Docker'],
        topics: [
          'Building HTTP REST APIs with net/http, Chi or Gin Routers',
          'JSON Request/Response Marshaling & Validation',
          'Database Connectivity with PostgreSQL (pgx / GORM)',
          'Middleware: Authentication, Logging, Rate Limiting & Recovery',
        ],
        practiceTasks: ['Build complete CRUD REST API in Go with PostgreSQL', 'Implement JWT authentication middleware in Go'],
        projects: ['Production RESTful Microservice with PostgreSQL & Docker in Go'],
        milestone: 'RESTful API and database persistence in Go operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: High-Speed gRPC & Protocol Buffers Communication (Advanced)',
        objective: 'Design low-latency microservices communication using Protocol Buffers and binary gRPC streaming.',
        durationWeeks: 4,
        skills: ['Go (Golang)', 'gRPC', 'Protocol Buffers', 'Microservices'],
        topics: [
          'Protobuf Schema Definition & Code Generation for Go',
          'Unary, Client Streaming & Server Streaming gRPC Handlers',
          'gRPC Interceptors for Auth, Tracing & Error Handling',
          'Benchmarking gRPC Throughput vs JSON REST APIs',
        ],
        practiceTasks: ['Build bidirectional streaming gRPC microservice in Go', 'Measure response latency under high concurrent load'],
        projects: ['Ultra Low-Latency gRPC Order Matching Microservices Engine in Go'],
        milestone: 'Binary gRPC microservices communication operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Kafka Event Streaming, Consensus & Capstone (Job-Ready)',
        objective: 'Implement event-driven streaming with Apache Kafka, Raft consensus principles, Docker deployment, and mentor mock interview.',
        durationWeeks: 3,
        skills: ['Kafka', 'Docker', 'System Design', 'Interview Prep'],
        topics: [
          'Kafka Event Streaming with Go (Sarama / Segmentio Kafka-Go)',
          'Transactional Outbox Pattern & Idempotent Message Processing',
          'Multi-Stage Docker Builds & Cloud Deployment',
          'Distributed Systems Technical Mock Interviews',
        ],
        practiceTasks: ['Implement event-driven streaming pipeline in Go with Kafka', 'Complete 1-on-1 distributed systems review with mentor Aditya Roy'],
        projects: ['Production Enterprise Distributed Event Platform in Go & Kafka'],
        milestone: 'Job-Ready Distributed Systems & Go Backend Engineer',
      },
    ],
    finalMilestone: 'Certified Distributed Systems & Go Engineer',
  },
];
