/**
 * @file roadmaps-catalog.ts
 * @description 10 Production-Grade Technical Career Roadmaps (Top to Bottom).
 * Stored in database, indexed in pgvector, and retrieved via semantic search & cross-entropy re-ranking.
 */

export interface RoadmapPhaseCatalogItem {
  phaseNumber: number;
  title: string;
  objective: string;
  durationWeeks: number;
  skills: string[];
  topics: string[];
  practiceTasks: string[];
  projects: string[];
  milestone: string;
}

export interface CareerRoadmapCatalogItem {
  id: string;
  slug: string;
  title: string;
  category: string;
  targetRole: string;
  level: string;
  estimatedDurationWeeks: number;
  summary: string;
  primarySkills: string[];
  phases: RoadmapPhaseCatalogItem[];
  finalMilestone: string;
}

export const PRODUCTION_ROADMAPS_CATALOG: CareerRoadmapCatalogItem[] = [
  {
    id: 'roadmap-fullstack-nextjs',
    slug: 'fullstack-nextjs-typescript',
    title: 'Full Stack Next.js 15 & TypeScript Architect',
    category: 'Full Stack',
    targetRole: 'Full Stack Engineer',
    level: 'Intermediate',
    estimatedDurationWeeks: 14,
    summary: 'Comprehensive top-to-bottom roadmap from modern React 19 and strict TypeScript to Next.js App Router, Prisma ORM, PostgreSQL transactions, and automated CI/CD deployment.',
    primarySkills: ['React', 'Next.js', 'TypeScript', 'PostgreSQL', 'Tailwind CSS', 'Docker'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Modern TypeScript, React 19 & Tailwind CSS Foundations',
        objective: 'Master strict TypeScript generics, React Server Components, custom hooks, and Tailwind CSS design tokens.',
        durationWeeks: 3,
        skills: ['TypeScript', 'React', 'Tailwind CSS'],
        topics: ['Generics & Utility Types', 'Server vs Client Components', 'Suspense & Error Boundaries', 'Tailwind CSS Tokens'],
        practiceTasks: ['Build a type-safe reusable design system component library', 'Implement custom state management hooks'],
        projects: ['Interactive Component Design System & Dashboard Shell'],
        milestone: 'Type-safe frontend UI component architecture verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Next.js App Router, Server Actions & PostgreSQL Persistence',
        objective: 'Design scalable relational schemas with Prisma ORM, write Server Actions, and implement secure JWT authentication.',
        durationWeeks: 4,
        skills: ['Next.js', 'PostgreSQL', 'Prisma ORM', 'REST APIs'],
        topics: ['App Router Layouts & Routing', 'Server Actions & Mutations', 'Relational Schemas & Foreign Keys', 'RBAC & Auth Middleware'],
        practiceTasks: ['Create full CRUD endpoints with Zod validation', 'Implement multi-role session protection with NextAuth/Jose'],
        projects: ['Professional Freelance Marketplace Platform with Relational Database'],
        milestone: 'Full stack data persistence and authentication flows operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Real-Time State, Caching & Performance Optimization',
        objective: 'Optimize data fetching with TanStack React Query, Redis caching, optimistic UI updates, and streaming.',
        durationWeeks: 4,
        skills: ['State Management', 'Redis', 'WebSockets', 'Performance Optimization'],
        topics: ['TanStack Query Cache Invalidation', 'Redis Key-Value Caching', 'Real-time WebSockets / SSE', 'Core Web Vitals Tuning'],
        practiceTasks: ['Achieve 95+ Google Lighthouse performance score', 'Implement instant chat and notification drawer'],
        projects: ['High-Performance Collaborative Real-Time Workspace with Redis Caching'],
        milestone: 'Sub-100ms response latency and real-time state synchronization verified',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Production Containerization, CI/CD & Capstone Portfolio',
        objective: 'Deploy with multi-stage Docker builds, automated GitHub Actions pipelines, and complete 1-on-1 mentor code review.',
        durationWeeks: 3,
        skills: ['Docker', 'CI/CD Pipelines', 'System Design', 'Interview Prep'],
        topics: ['Multi-stage Dockerfile Optimization', 'Automated GitHub Actions Testing', 'System Architecture Mock Interview'],
        practiceTasks: ['Set up 100% automated CI build & lint check pipeline', 'Conduct 1-on-1 code audit session with senior mentor'],
        projects: ['Production-Grade Enterprise SaaS Application with Complete CI/CD'],
        milestone: 'Job-Ready Full Stack Developer Portfolio Complete',
      },
    ],
    finalMilestone: 'Certified Full Stack Next.js & TypeScript Candidate',
  },
  {
    id: 'roadmap-backend-java-spring',
    slug: 'backend-java-spring-boot',
    title: 'Backend Java 21 & Spring Boot Microservices Architect',
    category: 'Backend',
    targetRole: 'Backend Java Architect',
    level: 'Advanced',
    estimatedDurationWeeks: 16,
    summary: 'Master enterprise distributed systems with Java 21 Virtual Threads, Spring Boot 3, Spring Data JPA, PostgreSQL optimization, and Apache Kafka messaging.',
    primarySkills: ['Java', 'Spring Boot', 'PostgreSQL', 'Docker', 'System Design', 'Kafka'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Advanced Java 21 & Concurrency Fundamentals',
        objective: 'Deepen object-oriented design patterns, Java 21 Virtual Threads (Project Loom), Stream API, and garbage collection tuning.',
        durationWeeks: 4,
        skills: ['Java', 'OOP', 'Concurrency', 'Design Patterns'],
        topics: ['Virtual Threads & Structured Concurrency', 'Generics & Reflection', 'Garbage Collection Algorithms', 'Thread-safe Collections'],
        practiceTasks: ['Implement lock-free thread-safe cache', 'Profile memory allocation and GC pauses with JProfiler'],
        projects: ['High-Throughput Multi-threaded Financial Order Processing Engine'],
        milestone: 'Advanced Java syntax and concurrent execution verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Spring Boot 3, Spring Data JPA & Microservices REST APIs',
        objective: 'Master Spring IoC, Controller Advice, Hibernate lazy loading, and OpenAPI/Swagger contracts.',
        durationWeeks: 4,
        skills: ['Spring Boot', 'Spring Data JPA', 'REST APIs', 'PostgreSQL'],
        topics: ['Dependency Injection & Spring Context', 'Hibernate N+1 Query Optimization', 'Transaction Management (@Transactional)', 'OpenAPI Documentation'],
        practiceTasks: ['Build enterprise REST microservice with JPA', 'Implement global validation and error response handlers'],
        projects: ['Banking & Payment Transaction Microservices Gateway'],
        milestone: 'Production-ready Spring Boot services operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Distributed Messaging, Kafka & PostgreSQL Optimization',
        objective: 'Implement event-driven architecture using Apache Kafka, Redis caching, and PostgreSQL query execution plans.',
        durationWeeks: 4,
        skills: ['Kafka', 'Redis', 'PostgreSQL', 'System Design'],
        topics: ['Kafka Producer/Consumer Partitions', 'Eventual Consistency & Saga Pattern', 'B-Tree Indexing & EXPLAIN ANALYZE', 'Redis Distributed Locks'],
        practiceTasks: ['Configure distributed Kafka topics with exactly-once semantics', 'Optimize slow queries and connection pool settings'],
        projects: ['Distributed Event-Driven Notification & Billing Cluster with Kafka'],
        milestone: 'Distributed messaging and database performance tuned',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Spring Security 6, Docker & System Design Interview Prep',
        objective: 'Harden microservices with OAuth2/JWT token introspection, containerize in Docker, and conduct system design mock interviews.',
        durationWeeks: 4,
        skills: ['Spring Security', 'Docker', 'Kubernetes', 'System Design'],
        topics: ['Spring Security 6 Stateless JWT Filters', 'OAuth2 / OIDC Integration', 'Multi-stage Docker Builds', 'CAP Theorem & Sharding'],
        practiceTasks: ['Write 90%+ code coverage unit tests with JUnit 5 and Mockito', 'Book 1-on-1 architecture review with senior mentor Priya Sharma'],
        projects: ['Production-Grade Enterprise Java Microservices Architecture'],
        milestone: 'Job-Ready Senior Java & Spring Boot Backend Engineer',
      },
    ],
    finalMilestone: 'Certified Java & Spring Boot Microservices Architect',
  },
  {
    id: 'roadmap-genai-llm-rag',
    slug: 'generative-ai-llm-rag',
    title: 'Generative AI, LangChain & LLM RAG Pipeline Specialist',
    category: 'AI / Machine Learning',
    targetRole: 'AI & LLM Engineer',
    level: 'Advanced',
    estimatedDurationWeeks: 14,
    summary: 'Build production generative AI copilots, custom vector embedding search with PostgreSQL pgvector, LangChain autonomous agent chains, and FastAPI backends.',
    primarySkills: ['Python', 'LangChain & RAG', 'LLM Engineering', 'PostgreSQL', 'FastAPI', 'PyTorch'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Python for AI, Vector Math & NumPy/PyTorch Foundations',
        objective: 'Master vectorized computing, PyTorch tensors, tokenization algorithms, and neural network embedding spaces.',
        durationWeeks: 3,
        skills: ['Python', 'PyTorch', 'Vector Embeddings', 'Data Science'],
        topics: ['Tensors & Vector Projections', 'Tokenizers (BPE & WordPiece)', 'Embedding Dimensionality & L2 Normalization', 'Cosine Similarity Metrics'],
        practiceTasks: ['Build custom vector projection and cosine search from scratch', 'Train custom embedding space on text data'],
        projects: ['Semantic Text Embedding & Nearest Neighbor Search Engine'],
        milestone: 'Vector mathematics and neural embeddings verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: RAG Architectures, Chunking & PostgreSQL pgvector Storage',
        objective: 'Design production Retrieval-Augmented Generation with document splitters, hybrid search, and pgvector cosine indexing.',
        durationWeeks: 4,
        skills: ['LangChain & RAG', 'PostgreSQL', 'Vector DBs', 'Python'],
        topics: ['Recursive Character Splitting & Semantic Chunking', 'pgvector <=> Cosine Operator & HNSW Indexes', 'Context Injection & Prompt Engineering', 'Reranking & Cross-Encoders'],
        practiceTasks: ['Ingest and index 1,000+ technical PDF documents into PostgreSQL', 'Implement hybrid keyword + vector retrieval pipeline'],
        projects: ['Enterprise Document Intelligence & RAG Chatbot with Citation Sources'],
        milestone: 'End-to-end grounded RAG pipeline operational with high recall',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Autonomous LangChain Agents, Tool Calling & Structured Outputs',
        objective: 'Orchestrate multi-step reasoning agents with tool calling, schema validation via Pydantic, and memory management.',
        durationWeeks: 4,
        skills: ['LangChain & RAG', 'LLM Engineering', 'FastAPI', 'Pydantic'],
        topics: ['ReAct Agent Architecture', 'Structured Output Parsing (Zod / Pydantic)', 'Tool Calling & API Integration', 'Hallucination Mitigation & Guardrails'],
        practiceTasks: ['Build autonomous agent capable of querying SQL databases and REST APIs', 'Implement token cost and latency telemetry'],
        projects: ['Autonomous Career & Code Review Copilot with Multi-Tool Execution'],
        milestone: 'Multi-agent tool orchestration and structured reasoning verified',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: MLOps, Async FastAPI Serving & Production Deployment',
        objective: 'Deploy LLM applications as high-throughput async FastAPI microservices with streaming SSE responses and Docker.',
        durationWeeks: 3,
        skills: ['FastAPI', 'Docker', 'MLOps', 'CI/CD Pipelines'],
        topics: ['Async FastAPI Endpoints & Streaming SSE', 'Model Quantization (GGUF / ONNX)', 'Containerization with Docker', 'Production LLM Benchmarks'],
        practiceTasks: ['Benchmark response latency under 100 concurrent users', 'Conduct 1-on-1 AI architecture review with mentor Sneha Iyer'],
        projects: ['Production Scalable Generative AI API Gateway with Real-Time Streaming'],
        milestone: 'Job-Ready Production Generative AI & RAG Engineer',
      },
    ],
    finalMilestone: 'Certified Generative AI & RAG Pipeline Specialist',
  },
  {
    id: 'roadmap-cloud-devops-k8s',
    slug: 'cloud-devops-kubernetes-sre',
    title: 'Cloud DevOps, Kubernetes & AWS Infrastructure SRE',
    category: 'DevOps & Cloud',
    targetRole: 'Cloud DevOps Architect',
    level: 'Advanced',
    estimatedDurationWeeks: 15,
    summary: 'Master infrastructure as code with Terraform, container orchestration on AWS EKS with Kubernetes, automated GitHub Actions CI/CD, and Prometheus/Grafana SRE monitoring.',
    primarySkills: ['Docker', 'Kubernetes', 'AWS', 'CI/CD Pipelines', 'System Design'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Linux Internals, Networking & Multi-Stage Docker Builds',
        objective: 'Master Linux kernel cgroups, namespaces, TCP/IP networking, and secure minimal Docker image builds.',
        durationWeeks: 3,
        skills: ['Docker', 'Linux', 'Networking', 'Shell Scripting'],
        topics: ['Linux Permissions & Process Management', 'IP Routing, DNS, Subnets & Firewalls', 'Multi-Stage Dockerfile Optimization', 'Container Security Hardening'],
        practiceTasks: ['Build sub-50MB production Docker image for Node.js/Java apps', 'Configure local container networking and volume mounts'],
        projects: ['Production-Hardened Microservices Container Suite'],
        milestone: 'Linux administration and container security verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Kubernetes Orchestration, Helm Charts & Service Meshes',
        objective: 'Deploy and manage microservices clusters with Kubernetes Pods, Deployments, Services, Ingress, and Helm packaging.',
        durationWeeks: 4,
        skills: ['Kubernetes', 'Docker', 'Helm', 'Cloud Native'],
        topics: ['Pods, ReplicaSets & StatefulSets', 'Ingress Controllers & SSL Termination', 'ConfigMaps, Secrets & RBAC', 'Helm Chart Packaging & Value Overrides'],
        practiceTasks: ['Deploy 5-tier microservices application on Kubernetes', 'Implement automated Horizontal Pod Autoscaling (HPA)'],
        projects: ['High-Availability Kubernetes Cluster with Automated Autoscaling'],
        milestone: 'Kubernetes cluster deployment and rolling updates operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Infrastructure as Code (Terraform) on AWS & Automated CI/CD',
        objective: 'Provision AWS VPCs, EKS clusters, and RDS databases using Terraform with automated GitHub Actions CI/CD pipelines.',
        durationWeeks: 4,
        skills: ['AWS', 'Terraform', 'CI/CD Pipelines', 'Cloud Architecture'],
        topics: ['Terraform State Management & Modules', 'AWS VPC, EKS, RDS, S3 & IAM Policies', 'GitHub Actions Automated CI/CD Workflows', 'Zero-Downtime Blue/Green Deployments'],
        practiceTasks: ['Write modular Terraform script to provision multi-AZ AWS infrastructure', 'Build end-to-end GitHub Actions pipeline deploying to EKS'],
        projects: ['Fully Automated AWS Infrastructure Provisioning & CI/CD Delivery Pipeline'],
        milestone: 'Infrastructure as Code and zero-downtime deployment pipelines verified',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Observability, Prometheus/Grafana SRE & Disaster Recovery',
        objective: 'Configure comprehensive telemetry, metric dashboards, alerting rules, and disaster recovery failover plans.',
        durationWeeks: 4,
        skills: ['Observability', 'Prometheus', 'Grafana', 'SRE Best Practices'],
        topics: ['Prometheus Metric Scraping & Alertmanager', 'Grafana SLO/SLA Dashboards', 'Distributed Tracing (OpenTelemetry)', 'Chaos Engineering & Backup Recovery'],
        practiceTasks: ['Set up 99.99% availability alert system for critical microservices', 'Complete 1-on-1 SRE architecture audit with mentor Arjun Nair'],
        projects: ['Production Enterprise Cloud SRE & Observability Platform'],
        milestone: 'Job-Ready Principal Cloud DevOps & SRE Engineer',
      },
    ],
    finalMilestone: 'Certified Cloud DevOps & Kubernetes SRE Specialist',
  },
  {
    id: 'roadmap-frontend-uiux-react',
    slug: 'frontend-uiux-design-systems',
    title: 'Frontend React 19 & UI/UX Design System Lead',
    category: 'Frontend',
    targetRole: 'Senior Frontend Engineer',
    level: 'Intermediate',
    estimatedDurationWeeks: 12,
    summary: 'Design scalable design token libraries in Figma, engineer accessible React 19 component primitives with Tailwind CSS, and optimize Core Web Vitals to 95+.',
    primarySkills: ['React', 'TypeScript', 'UI/UX Design (Figma)', 'Tailwind CSS', 'Next.js'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Figma Token Architecture, Design Systems & Handoff',
        objective: 'Create unified color, typography, spacing tokens, and component variants in Figma with auto-layout.',
        durationWeeks: 3,
        skills: ['UI/UX Design (Figma)', 'Design Systems', 'Accessibility'],
        topics: ['Design Tokens & Variable Modes (Dark/Light)', 'Auto-layout & Component Variants', 'WCAG 2.1 AA Accessibility Standards', 'Design to Code Handoff Workflows'],
        practiceTasks: ['Build comprehensive Figma design system with 30+ reusable primitives', 'Audit color contrast ratios for accessibility compliance'],
        projects: ['Enterprise Figma Design System & Interactive UI Kit'],
        milestone: 'Design system tokens and responsive layouts verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: React 19 Components, Tailwind CSS & Motion Animations',
        objective: 'Translate Figma tokens into pixel-perfect React 19 component libraries with Tailwind CSS and Framer Motion.',
        durationWeeks: 3,
        skills: ['React', 'Tailwind CSS', 'TypeScript', 'Framer Motion'],
        topics: ['Compound Component Pattern in React', 'Tailwind Variants & Class Variance Authority', 'Micro-interactions & Smooth Transitions', 'Keyboard Navigation & ARIA Attributes'],
        practiceTasks: ['Build accessible modal, dropdown, and data table components', 'Implement fluid spring animations and page transitions'],
        projects: ['Production React Component Library with Storybook Documentation'],
        milestone: 'Accessible and animated UI component suite complete',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Next.js App Router, TanStack Query & Data Visualization',
        objective: 'Assemble responsive data dashboards with Next.js App Router, TanStack Query caching, and Recharts analytics.',
        durationWeeks: 3,
        skills: ['Next.js', 'TanStack Query', 'Data Visualization', 'TypeScript'],
        topics: ['App Router Layouts & Nested Routes', 'TanStack Query Optimistic Updates', 'Interactive Data Visualizations (Recharts/D3)', 'Form Validation with React Hook Form & Zod'],
        practiceTasks: ['Build dynamic analytics dashboard with live filtering', 'Implement type-safe multi-step wizard form'],
        projects: ['Real-Time SaaS Analytics Dashboard & Reporting Suite'],
        milestone: 'Complex data dashboard and state synchronization operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Web Vitals Performance Audit, E2E Testing & Portfolio Review',
        objective: 'Audit Core Web Vitals (LCP, CLS, INP), write Playwright end-to-end tests, and conduct 1-on-1 portfolio review with mentor.',
        durationWeeks: 3,
        skills: ['Web Performance', 'Playwright', 'Interview Prep', 'Mentorship'],
        topics: ['Bundle Optimization & Code Splitting', 'Lighthouse 95+ Tuning', 'Automated E2E Testing with Playwright', 'Live Portfolio Demonstration'],
        practiceTasks: ['Pass 100% automated E2E browser tests', 'Complete 1-on-1 portfolio audit with mentor Ananya Deshmukh'],
        projects: ['High-Performance Digital Product Portfolio with 98+ Lighthouse Score'],
        milestone: 'Job-Ready Senior Frontend Engineer & UI/UX Specialist',
      },
    ],
    finalMilestone: 'Certified Frontend & UI/UX Design System Specialist',
  },
  {
    id: 'roadmap-mobile-flutter-react-native',
    slug: 'mobile-app-development-flutter',
    title: 'Cross-Platform Mobile App Architect (Flutter & React Native)',
    category: 'Mobile Development',
    targetRole: 'Mobile App Developer',
    level: 'Intermediate',
    estimatedDurationWeeks: 14,
    summary: 'Build high-performance iOS and Android native mobile applications with Flutter, Dart, React Native, Expo Router, and offline SQLite caching.',
    primarySkills: ['Flutter', 'React Native', 'Mobile Development', 'TypeScript', 'Firebase'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Flutter & Dart Fundamentals or React Native / Expo',
        objective: 'Master mobile widget trees, reactive state management, and navigation routing.',
        durationWeeks: 3,
        skills: ['Flutter', 'Dart', 'React Native', 'TypeScript'],
        topics: ['Widget Tree & Lifecycle', 'Riverpod / Redux State Management', 'Expo Router & Navigation Stacks', 'Adaptive UI for iOS and Android'],
        practiceTasks: ['Build cross-platform mobile UI with custom animations', 'Implement dark/light theme switching'],
        projects: ['Cross-Platform Mobile Habits & Task Tracking App'],
        milestone: 'Mobile UI architecture and responsive layouts verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Local Database Persistence, Caching & Offline-First UX',
        objective: 'Implement local SQLite / Hive storage, background sync, and offline data synchronization.',
        durationWeeks: 4,
        skills: ['SQLite', 'Offline Storage', 'REST APIs', 'GraphQL'],
        topics: ['Local Database Caching (SQLite/Hive)', 'Network Connectivity Listeners', 'Offline Queue & Conflict Resolution', 'REST & GraphQL Mobile Clients'],
        practiceTasks: ['Build offline-first data synchronization engine', 'Implement local image caching and pagination'],
        projects: ['Offline-First E-Commerce & Inventory Mobile App'],
        milestone: 'Offline-first persistence and caching verified',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Native Device Hardware APIs, Push Notifications & Security',
        objective: 'Integrate native device sensors (GPS, Camera, Biometrics), Firebase Cloud Messaging, and secure keychain storage.',
        durationWeeks: 4,
        skills: ['Firebase', 'Mobile Security', 'Geolocation', 'Biometrics'],
        topics: ['Biometric Face/Fingerprint Authentication', 'Geolocation & Live Map Tracking', 'Firebase Push Notifications', 'Secure Keychain / Keystore Storage'],
        practiceTasks: ['Implement biometric app lock and encrypted storage', 'Setup automated push notifications with deep linking'],
        projects: ['Location-Aware On-Demand Delivery & Ride Tracking Mobile App'],
        milestone: 'Hardware sensor integration and biometric security verified',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Automated Testing, CI/CD Fastlane & App Store Publishing',
        objective: 'Automate build, test, and release pipelines using Fastlane, Appium, and publish to Apple App Store and Google Play.',
        durationWeeks: 3,
        skills: ['CI/CD Pipelines', 'App Store Deploy', 'Fastlane', 'Mentorship'],
        topics: ['Automated UI Testing with Maestro/Appium', 'Fastlane Automated Code Signing', 'Google Play & App Store Compliance', 'Live App Architecture Review with Mentor'],
        practiceTasks: ['Build automated Fastlane release pipeline', 'Complete 1-on-1 code audit with mentor Pooja Verma'],
        projects: ['Production Published Mobile App on App Store & Google Play'],
        milestone: 'Job-Ready Mobile Application Architect',
      },
    ],
    finalMilestone: 'Certified Mobile App Architect (Flutter & React Native)',
  },
  {
    id: 'roadmap-data-engineering-etl',
    slug: 'data-engineering-postgresql-etl',
    title: 'Data Engineering & Real-Time ETL Pipeline Specialist',
    category: 'Database & Architecture',
    targetRole: 'Data Engineer',
    level: 'Advanced',
    estimatedDurationWeeks: 14,
    summary: 'Design high-volume distributed data pipelines, partitioned PostgreSQL architectures, Apache Kafka streaming, and business intelligence metrics.',
    primarySkills: ['Python', 'PostgreSQL', 'Redis', 'Kafka', 'System Design'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Advanced SQL, Schema Normalization & Query Tuning',
        objective: 'Master PostgreSQL window functions, recursive CTEs, declarative table partitioning, and query execution plans.',
        durationWeeks: 3,
        skills: ['PostgreSQL', 'SQL Optimization', 'Database Indexing'],
        topics: ['Window Functions & Aggregations', 'Declarative Range & List Partitioning', 'B-Tree, GIN, and GiST Indexes', 'Query Plan Profiling with EXPLAIN'],
        practiceTasks: ['Partition a 10M+ row table and measure query speedups', 'Write recursive SQL queries for hierarchical data'],
        projects: ['High-Performance Partitioned Time-Series Telemetry Database'],
        milestone: 'Advanced SQL mastery and query optimization verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Python ETL Pipelines, Data Validation & Batch Processing',
        objective: 'Build robust ETL data pipelines in Python with Pandas, Polars, and schema validation with Great Expectations.',
        durationWeeks: 4,
        skills: ['Python', 'Data Engineering', 'ETL Pipelines', 'Pandas'],
        topics: ['Data Extraction from REST APIs & SQL', 'Vectorized Transformations with Polars/Pandas', 'Data Quality Assertions & Anomaly Detection', 'Batch Scheduling & Idempotency'],
        practiceTasks: ['Build automated pipeline ingesting messy real-world datasets', 'Implement automated data schema validation rules'],
        projects: ['Automated Multi-Source Financial Data Ingestion & ETL Pipeline'],
        milestone: 'Robust batch ETL extraction and validation verified',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Real-Time Stream Processing with Apache Kafka & Redis',
        objective: 'Process live data streams with Kafka consumers, Redis caching, and real-time aggregation metrics.',
        durationWeeks: 4,
        skills: ['Kafka', 'Redis', 'Stream Processing', 'System Design'],
        topics: ['Kafka Event Streaming & Partitions', 'Sliding Window Aggregations', 'Redis In-Memory Analytics & HyperLogLog', 'Exactly-Once Processing Guarantees'],
        practiceTasks: ['Build real-time telemetry streaming engine with Kafka', 'Configure Redis leaderboard and real-time metric counter'],
        projects: ['Real-Time High-Throughput E-Commerce Telemetry & Analytics Engine'],
        milestone: 'Real-time event streaming and sub-second metrics operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Cloud Data Warehousing, CI/CD & Portfolio Capstone',
        objective: 'Deploy automated data pipelines with Docker, monitoring, and conduct 1-on-1 architecture review with senior mentor.',
        durationWeeks: 3,
        skills: ['Docker', 'CI/CD Pipelines', 'System Design', 'Interview Prep'],
        topics: ['Containerized Pipeline Orchestration', 'Data Lineage & Metadata Tracking', 'Mock Data Engineering System Design Interview'],
        practiceTasks: ['Pass automated regression tests on all pipeline stages', 'Book 1-on-1 architecture review with mentor Karthik Raja'],
        projects: ['Enterprise Data Lakehouse & Real-Time Analytics Platform'],
        milestone: 'Job-Ready Enterprise Data Engineer',
      },
    ],
    finalMilestone: 'Certified Data Engineering & Pipeline Specialist',
  },
  {
    id: 'roadmap-cybersecurity-oauth2',
    slug: 'cybersecurity-zero-trust-cloud',
    title: 'Cybersecurity, OAuth2 & Zero-Trust Cloud Defense Specialist',
    category: 'Backend',
    targetRole: 'Cybersecurity Engineer',
    level: 'Advanced',
    estimatedDurationWeeks: 12,
    summary: 'Protect modern web applications against OWASP Top 10 vulnerabilities, implement zero-trust OAuth2/OIDC token architectures, and secure container runtimes.',
    primarySkills: ['Cybersecurity', 'Spring Security', 'Docker', 'System Design', 'AWS'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: OWASP Top 10 Defense, Threat Modeling & Secure Coding',
        objective: 'Audit and remediate SQL injection, XSS, CSRF, broken access control, and cryptographic failures.',
        durationWeeks: 3,
        skills: ['Cybersecurity', 'Secure Coding', 'Web Security'],
        topics: ['OWASP Top 10 Vulnerabilities', 'Input Sanitization & Parameterized Queries', 'Content Security Policy (CSP) & CORS Headers', 'Threat Modeling & STRIDE Framework'],
        practiceTasks: ['Conduct penetration test on intentionally vulnerable web app', 'Remediate 10 security vulnerabilities and verify with OWASP ZAP'],
        projects: ['Web Application Vulnerability Scanner & Remediation Report'],
        milestone: 'OWASP vulnerability remediation and defense verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: OAuth2, OIDC & Stateless Token Architecture',
        objective: 'Implement production OAuth2 authentication servers, PKCE flows, JWT verification, and RBAC authorization.',
        durationWeeks: 3,
        skills: ['Spring Security', 'OAuth2', 'JWT', 'Authentication'],
        topics: ['OAuth2 Authorization Code Flow with PKCE', 'OpenID Connect (OIDC) Identity Claims', 'Cryptographic JWT Signing & Verification (RS256)', 'Fine-Grained Role-Based Access Control (RBAC)'],
        practiceTasks: ['Build dedicated OAuth2 token authorization server', 'Implement cryptographic key rotation and token introspection'],
        projects: ['Enterprise Centralized OAuth2 / OIDC Single Sign-On (SSO) Gateway'],
        milestone: 'Cryptographic identity and token verification operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Container Security, Secrets Management & Zero-Trust Cloud',
        objective: 'Secure Docker container images, enforce secrets management, and configure zero-trust network policies.',
        durationWeeks: 3,
        skills: ['Docker', 'AWS', 'Secrets Management', 'Kubernetes'],
        topics: ['Container Vulnerability Scanning (Trivy)', 'Secrets Management (AWS Secrets Manager / Vault)', 'mTLS & Service-to-Service Encryption', 'Least Privilege IAM Security Policies'],
        practiceTasks: ['Scan Docker images and achieve 0 high/critical CVEs', 'Implement mTLS encrypted communication between microservices'],
        projects: ['Zero-Trust Microservices Security Architecture with mTLS & Vault'],
        milestone: 'Zero-trust infrastructure and container hardening verified',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Security Audit, Incident Response & Portfolio Capstone',
        objective: 'Simulate incident response, audit access logs, and complete 1-on-1 security review with senior cybersecurity mentor.',
        durationWeeks: 3,
        skills: ['Incident Response', 'Security Auditing', 'Interview Prep', 'Mentorship'],
        topics: ['Security Event Logging & SIEM Analysis', 'Incident Response Runbooks', 'Live Security Audit Demonstration with Mentor'],
        practiceTasks: ['Draft comprehensive security audit and incident response runbook', 'Conduct 1-on-1 security review with mentor Suresh Menon'],
        projects: ['Production Enterprise Zero-Trust Defense & Security Audit Suite'],
        milestone: 'Job-Ready Cybersecurity & Cloud Defense Specialist',
      },
    ],
    finalMilestone: 'Certified Cybersecurity & Zero-Trust Defense Engineer',
  },
  {
    id: 'roadmap-db-performance-redis',
    slug: 'database-performance-redis-caching',
    title: 'Database Performance, Indexing & Redis Caching Architect',
    category: 'Database & Architecture',
    targetRole: 'Database Architect',
    level: 'Advanced',
    estimatedDurationWeeks: 12,
    summary: 'Optimize high-throughput relational databases with B-Tree indexes, query execution plan tuning, and sub-millisecond Redis distributed caching.',
    primarySkills: ['PostgreSQL', 'Redis', 'System Design', 'Database & Architecture'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Relational Theory, B-Tree Indexing & Explain Plans',
        objective: 'Master B-Tree index structure, composite indexes, covering indexes, and EXPLAIN ANALYZE execution cost interpretation.',
        durationWeeks: 3,
        skills: ['PostgreSQL', 'Database Indexing', 'SQL Optimization'],
        topics: ['B-Tree, Hash, GIN & BRIN Index Mechanics', 'Composite Index Column Ordering Rules', 'Index Scan vs Bitmap Index Scan vs Seq Scan', 'Interpreting EXPLAIN (ANALYZE, BUFFERS) Plans'],
        practiceTasks: ['Optimize slow queries from 2.5s down to <5ms using composite indexes', 'Profile buffer cache hit ratios in PostgreSQL'],
        projects: ['Database Query Optimization & Performance Benchmark Report'],
        milestone: 'B-Tree indexing and query plan optimization verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: Transactions, Isolation Levels & Lock Contention',
        objective: 'Master ACID transaction isolation levels, row-level locks, MVCC concurrency, and deadlocks resolution.',
        durationWeeks: 3,
        skills: ['PostgreSQL', 'ACID Transactions', 'Concurrency'],
        topics: ['Read Committed vs Repeatable Read vs Serializable', 'Multi-Version Concurrency Control (MVCC)', 'Row-level Locks (FOR UPDATE) & Deadlock Avoidance', 'Connection Pooling Optimization (HikariCP / PgBouncer)'],
        practiceTasks: ['Simulate high-concurrency race condition and resolve with serializable isolation', 'Configure PgBouncer connection pooling under 1,000 clients'],
        projects: ['High-Concurrency Financial Ledger with Zero Race Conditions'],
        milestone: 'Transaction concurrency and lock contention eliminated',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Redis In-Memory Architectures & Distributed Caching Patterns',
        objective: 'Design high-speed caching layers with Redis strings, hashes, sorted sets, pub/sub, and Redlock distributed locking.',
        durationWeeks: 3,
        skills: ['Redis', 'Distributed Caching', 'System Design'],
        topics: ['Cache-Aside, Write-Through & Write-Behind Patterns', 'Cache Stampede Mitigation & Mutex Locks', 'Distributed Locking with Redlock Algorithm', 'Redis Sentinel & High-Availability Clusters'],
        practiceTasks: ['Implement cache-aside pattern with automatic cache invalidation', 'Build distributed rate limiter using Redis sorted sets'],
        projects: ['Low-Latency Distributed Redis Cache Layer with Sentinel Failover'],
        milestone: 'Sub-millisecond distributed caching operational',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Sharding, Replication & System Architecture Capstone',
        objective: 'Implement PostgreSQL logical replication, horizontal sharding strategies, and complete 1-on-1 review with mentor.',
        durationWeeks: 3,
        skills: ['PostgreSQL', 'Replication', 'System Design', 'Mentorship'],
        topics: ['Read Replica Load Balancing', 'Logical Replication & Change Data Capture (CDC)', 'Horizontal Sharding Patterns', 'Mock Database Architecture Interview'],
        practiceTasks: ['Configure primary-replica streaming replication on PostgreSQL', 'Complete 1-on-1 database design review with mentor Karthik Raja'],
        projects: ['Enterprise Scalable Multi-Node Database & Cache Cluster Architecture'],
        milestone: 'Job-Ready Principal Database & Storage Architect',
      },
    ],
    finalMilestone: 'Certified Database Performance & Caching Specialist',
  },
  {
    id: 'roadmap-distributed-systems-go',
    slug: 'distributed-systems-golang-kafka',
    title: 'Distributed Systems & Event-Driven Go (Golang) Engineer',
    category: 'Backend',
    targetRole: 'Distributed Systems Architect',
    level: 'Advanced',
    estimatedDurationWeeks: 15,
    summary: 'Build ultra-fast backend microservices in Go (Golang), high-throughput gRPC interfaces, Apache Kafka event streaming, and fault-tolerant consensus.',
    primarySkills: ['Go (Golang)', 'System Design', 'Kafka', 'Docker', 'PostgreSQL'],
    phases: [
      {
        phaseNumber: 1,
        title: 'Phase 1: Go (Golang) Concurrency, Goroutines & Channels',
        objective: 'Master Go memory model, goroutines, buffered channels, mutexes, and race condition detection.',
        durationWeeks: 3,
        skills: ['Go (Golang)', 'Concurrency', 'Clean Architecture'],
        topics: ['Goroutines & Channel Synchronization', 'Select Statements & Context Cancellation', 'sync.Mutex, sync.RWMutex & sync.Pool', 'Benchmarking with go test -bench -race'],
        practiceTasks: ['Build concurrent worker pool processing 50,000 tasks/sec', 'Profile CPU and heap allocations using pprof'],
        projects: ['High-Performance Concurrent Worker Pool in Go'],
        milestone: 'Go concurrency and memory profiling verified',
      },
      {
        phaseNumber: 2,
        title: 'Phase 2: High-Speed gRPC & Protocol Buffers Microservices',
        objective: 'Design low-latency microservices communication using Protocol Buffers and binary gRPC streaming.',
        durationWeeks: 4,
        skills: ['Go (Golang)', 'gRPC', 'Protocol Buffers', 'PostgreSQL'],
        topics: ['Protobuf Schema Definition & Code Generation', 'Unary, Client Streaming & Server Streaming gRPC', 'gRPC Interceptors for Auth & Logging', 'Database Connection Management with pgx'],
        practiceTasks: ['Build bidirectional streaming gRPC microservice in Go', 'Benchmark gRPC throughput vs JSON REST endpoints'],
        projects: ['Ultra Low-Latency gRPC Order Matching Microservices Engine'],
        milestone: 'Binary gRPC microservices communication operational',
      },
      {
        phaseNumber: 3,
        title: 'Phase 3: Event-Driven Kafka Streaming & Distributed Transactions',
        objective: 'Implement event-driven streaming with Apache Kafka, consumer groups, partition balancing, and Saga patterns.',
        durationWeeks: 4,
        skills: ['Kafka', 'Go (Golang)', 'Event-Driven Architecture', 'System Design'],
        topics: ['Kafka Partitioning & Consumer Rebalancing', 'Outbox Pattern for Reliable Event Publishing', 'Saga Orchestration for Distributed Transactions', 'Idempotent Consumer Deduplication'],
        practiceTasks: ['Implement transactional outbox pattern in Go with PostgreSQL', 'Handle poison-pill messages and dead letter queues in Kafka'],
        projects: ['Distributed Event Streaming & Financial Settlement System in Go & Kafka'],
        milestone: 'Fault-tolerant event streaming and transaction consistency verified',
      },
      {
        phaseNumber: 4,
        title: 'Phase 4: Consensus Algorithms, Containerization & Portfolio Capstone',
        objective: 'Understand Raft consensus, containerize in Docker, and conduct 1-on-1 distributed system architecture review with mentor.',
        durationWeeks: 4,
        skills: ['Distributed Systems', 'Docker', 'System Design', 'Mentorship'],
        topics: ['Raft Consensus Algorithm & Leader Election', 'Distributed Tracing with OpenTelemetry in Go', 'System Design Mock Interviews for FAANG/Tier-1 Tech', 'Live Code Audit with Senior Mentor'],
        practiceTasks: ['Implement simplified Raft leader election prototype in Go', 'Complete 1-on-1 distributed systems review with mentor Aditya Roy'],
        projects: ['Production Enterprise Distributed Event Platform in Go & Kafka'],
        milestone: 'Job-Ready Distributed Systems & Go Backend Engineer',
      },
    ],
    finalMilestone: 'Certified Distributed Systems & Go Engineer',
  },
];
